/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ahmed
 */
public class Exam extends javax.swing.JFrame {

    /**
     * Creates new form Exam
     */
    public Exam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Question1 = new javax.swing.JLabel();
        Question2 = new javax.swing.JLabel();
        Question3 = new javax.swing.JLabel();
        Question4 = new javax.swing.JLabel();
        Question5 = new javax.swing.JLabel();
        RadioButton1 = new javax.swing.JRadioButton();
        RadioButton2 = new javax.swing.JRadioButton();
        RadioButton3 = new javax.swing.JRadioButton();
        RadioButton4 = new javax.swing.JRadioButton();
        RadioButton5 = new javax.swing.JRadioButton();
        RadioButton6 = new javax.swing.JRadioButton();
        RadioButton7 = new javax.swing.JRadioButton();
        RadioButton8 = new javax.swing.JRadioButton();
        RadioButton9 = new javax.swing.JRadioButton();
        RadioButton10 = new javax.swing.JRadioButton();
        ButtonFinish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Question1.setText("jLabel1");
        jPanel2.add(Question1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 470, -1));

        Question2.setText("jLabel2");
        jPanel2.add(Question2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 480, -1));

        Question3.setText("jLabel3");
        jPanel2.add(Question3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 480, -1));

        Question4.setText("jLabel4");
        jPanel2.add(Question4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 490, -1));

        Question5.setText("jLabel5");
        jPanel2.add(Question5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 480, -1));

        buttonGroup1.add(RadioButton1);
        RadioButton1.setText("True");
        jPanel2.add(RadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 68, 51, -1));

        buttonGroup1.add(RadioButton2);
        RadioButton2.setText("False");
        jPanel2.add(RadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 68, -1, -1));

        buttonGroup2.add(RadioButton3);
        RadioButton3.setText("True");
        RadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(RadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 159, 51, -1));

        buttonGroup2.add(RadioButton4);
        RadioButton4.setText("False");
        jPanel2.add(RadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        buttonGroup3.add(RadioButton5);
        RadioButton5.setText("True");
        jPanel2.add(RadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 51, -1));

        buttonGroup3.add(RadioButton6);
        RadioButton6.setText("False");
        jPanel2.add(RadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        buttonGroup4.add(RadioButton7);
        RadioButton7.setText("True");
        jPanel2.add(RadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 51, -1));

        buttonGroup4.add(RadioButton8);
        RadioButton8.setText("False");
        jPanel2.add(RadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        buttonGroup5.add(RadioButton9);
        RadioButton9.setText("True");
        RadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(RadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 51, -1));

        buttonGroup5.add(RadioButton10);
        RadioButton10.setText("False");
        jPanel2.add(RadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        ButtonFinish.setText("Finish");
        ButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFinishActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 472, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Answer this questions by ( true or false )");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 10, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void ButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFinishActionPerformed
        int counter;
        PrintWriter result= null;
        counter=0;
        if(RadioButton1.isSelected()){counter++;}
        if(RadioButton3.isSelected()){counter++;}
        if(RadioButton6.isSelected()){counter++;}
        if(RadioButton8.isSelected()){counter++;}
        if(RadioButton9.isSelected()){counter++;}
        JOptionPane.showMessageDialog(this,"your marks="+counter+"/5");
        try {
            result = new PrintWriter(new FileWriter ("result.txt",true));
            result.println(student_name.getName());
            result.println(counter);
            result.close();
        } 
        catch (IOException ex) {
            Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
        }
        Student_Page s1 = new Student_Page();
            s1.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_ButtonFinishActionPerformed

    private void RadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton3ActionPerformed

    private void RadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton9ActionPerformed
    public void set_exam(){
    try{
        Scanner read=new Scanner(new File("questions.txt"));
        Question1.setText(read.nextLine());
        Question2.setText(read.nextLine());
        Question3.setText(read.nextLine());
        Question4.setText(read.nextLine());
        Question5.setText(read.nextLine());
        read.close();
    }
    catch(IOException e){
        System.err.println("error");}
    }
     
     
     
     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonFinish;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question4;
    private javax.swing.JLabel Question5;
    private javax.swing.JRadioButton RadioButton1;
    private javax.swing.JRadioButton RadioButton10;
    private javax.swing.JRadioButton RadioButton2;
    private javax.swing.JRadioButton RadioButton3;
    private javax.swing.JRadioButton RadioButton4;
    private javax.swing.JRadioButton RadioButton5;
    private javax.swing.JRadioButton RadioButton6;
    private javax.swing.JRadioButton RadioButton7;
    private javax.swing.JRadioButton RadioButton8;
    private javax.swing.JRadioButton RadioButton9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
