/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author amwah
 */
public class Teacher_Page extends javax.swing.JFrame {

    
    public Teacher_Page() {
        initComponents();
        ButtonChoosefile.setVisible(false);
        TextfieldLink.setVisible(false);
        ButtonDone.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonAddAssignment = new javax.swing.JButton();
        ButtonAddLecture = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TextfieldLink = new javax.swing.JTextField();
        ButtonChoosefile = new javax.swing.JButton();
        ButtonDone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonLogOut = new javax.swing.JButton();
        ButtonChoosevideo = new javax.swing.JButton();
        ButtonAddExam = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ButtonAddAssignment.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAddAssignment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ButtonAddAssignment.setText("Add Assigment");
        ButtonAddAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddAssignmentActionPerformed(evt);
            }
        });

        ButtonAddLecture.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAddLecture.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ButtonAddLecture.setText("Add Lecture");
        ButtonAddLecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddLectureActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("Teacher Page");

        TextfieldLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldLinkActionPerformed(evt);
            }
        });

        ButtonChoosefile.setBackground(new java.awt.Color(255, 255, 255));
        ButtonChoosefile.setText("Choose file");
        ButtonChoosefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChoosefileActionPerformed(evt);
            }
        });

        ButtonDone.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDone.setText("Done");
        ButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDoneActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/presentation.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/academy2_2x (3).jpg"))); // NOI18N

        ButtonLogOut.setText("Log Out");
        ButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogOutActionPerformed(evt);
            }
        });

        ButtonChoosevideo.setBackground(new java.awt.Color(255, 255, 255));
        ButtonChoosevideo.setText("Choose Video");
        ButtonChoosevideo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonChoosevideo.setVisible(false);
        ButtonChoosevideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChoosevideoActionPerformed(evt);
            }
        });

        ButtonAddExam.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAddExam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonAddExam.setText("Add Exam");
        ButtonAddExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddExamActionPerformed(evt);
            }
        });

        ButtonBack.setText("back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(ButtonAddAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ButtonAddLecture, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAddExam, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextfieldLink, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 208, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ButtonLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(84, 84, 84))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonChoosefile, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonChoosevideo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(495, 495, 495))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonDone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(484, 484, 484))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonAddAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonAddLecture, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonAddExam)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextfieldLink, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonChoosefile))
                .addGap(18, 18, 18)
                .addComponent(ButtonChoosevideo)
                .addGap(18, 18, 18)
                .addComponent(ButtonDone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonLogOut)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBack)))
                .addContainerGap(320, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    private void ButtonAddLectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddLectureActionPerformed
        ButtonAddAssignment.setVisible(false);
        ButtonChoosefile.setVisible(false);
        ButtonChoosevideo.setVisible(true);
        ButtonDone.setVisible(true);
        ButtonAddExam.setVisible(false);
        TextfieldLink.setVisible(true);
    }//GEN-LAST:event_ButtonAddLectureActionPerformed

    private void ButtonAddAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddAssignmentActionPerformed
         ButtonAddLecture.setVisible(false);
         ButtonChoosefile.setVisible(true);
         ButtonChoosevideo.setVisible(false);
         ButtonDone.setVisible(true);
          ButtonAddExam.setVisible(false);
         TextfieldLink.setVisible(true);
    }//GEN-LAST:event_ButtonAddAssignmentActionPerformed

    private void TextfieldLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldLinkActionPerformed

    private void ButtonChoosefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChoosefileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String fn = f.getAbsolutePath();
        TextfieldLink.setText(fn);
        try { 
            PrintWriter out = new PrintWriter(new FileWriter("newFile.txt",true));
            out.println(fn);
            out.close();
        } 
        catch (Exception ex) {
            Logger.getLogger(Teacher_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonChoosefileActionPerformed

    private void ButtonChoosevideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChoosevideoActionPerformed
 JFileChooser chooser1 = new JFileChooser();
        chooser1.showOpenDialog(null);
        File f1 = chooser1.getSelectedFile();
        String fnn = f1.getAbsolutePath();
        TextfieldLink.setText(fnn);
        try { 
            PrintWriter out = new PrintWriter(new FileWriter("newVideoFile.txt"));
            out.println(fnn);
            out.close();
        } 
        catch (Exception ex) {
            Logger.getLogger(Teacher_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
               ButtonDone.setVisible(true);    }//GEN-LAST:event_ButtonChoosevideoActionPerformed

    private void ButtonAddExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddExamActionPerformed
    Add_Exam a1=new Add_Exam();
    this.setVisible(false);
    a1.setVisible(true);
    }//GEN-LAST:event_ButtonAddExamActionPerformed

    private void ButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogOutActionPerformed
    Menu m1=new Menu();
    this.setVisible(false);
    m1.setVisible(true);

    }//GEN-LAST:event_ButtonLogOutActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        ButtonAddAssignment.setVisible(true);
        ButtonAddLecture.setVisible(true); 
        ButtonAddExam.setVisible(true);
        TextfieldLink.setVisible(false);
        ButtonChoosefile.setVisible(false);
        ButtonChoosevideo.setVisible(false);
        ButtonDone.setVisible(false);
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDoneActionPerformed
        Teacher_Page t2=new Teacher_Page();
        this.setVisible(false);
        t2.setVisible(true);
    }//GEN-LAST:event_ButtonDoneActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddAssignment;
    private javax.swing.JButton ButtonAddExam;
    private javax.swing.JButton ButtonAddLecture;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonChoosefile;
    private javax.swing.JButton ButtonChoosevideo;
    private javax.swing.JButton ButtonDone;
    private javax.swing.JButton ButtonLogOut;
    private javax.swing.JTextField TextfieldLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
